const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Anchor,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.NinePatch,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.PlatformInfo,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Acts.SetFontFace,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.Browser.Exps.Language,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.NinePatch.Cnds.PickByUID,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.ZMoveToObject,
		C3.Plugins.Particles.Acts.SetDefaultColor,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Behaviors.DragnDrop.Cnds.IsEnabled,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{Anchor: 0},
	{btn_exit: 0},
	{TiledBackground: 0},
	{source: 0},
	{buttonsss: 0},
	{btnLeaderboard: 0},
	{Sine: 0},
	{GameLogo: 0},
	{backgroundMenu: 0},
	{MobForMenu1: 0},
	{MobForMenu2: 0},
	{MobForMenu3: 0},
	{MobForMenu4: 0},
	{MobForMenu6: 0},
	{MobForMenu7: 0},
	{btnPlay: 0},
	{boardSettings: 0},
	{btnClose: 0},
	{btnFullscreen: 0},
	{btnLanguage: 0},
	{btnSound: 0},
	{"9patch": 0},
	{LogoBestScoretext: 0},
	{LogoTextLanguage: 0},
	{TextLogoScore: 0},
	{numer2: 0},
	{numer3: 0},
	{Texts: 0},
	{Avatar1: 0},
	{Avatar10: 0},
	{Avatar2: 0},
	{Avatar3: 0},
	{Avatar4: 0},
	{Avatar5: 0},
	{Avatar6: 0},
	{Avatar7: 0},
	{Avatar8: 0},
	{Avatar9: 0},
	{boardLeaderboard: 0},
	{btnCloseLeaderboard: 0},
	{linePosPlayer: 0},
	{HighScoreLogo: 0},
	{btnHome: 0},
	{GameBackground: 0},
	{spawnCard: 0},
	{Xstart: 0},
	{Ystart: 0},
	{DragDrop: 0},
	{ic_card_: 0},
	{lineCard: 0},
	{ScoreText: 0},
	{LockParticles: 0},
	{numer: 0},
	{ScoreLogo: 0},
	{boardGameOver: 0},
	{btnOverHome: 0},
	{btnOverRetry: 0},
	{OverLogo: 0},
	{Audio: 0},
	{Touch: 0},
	{Browser: 0},
	{AJAX: 0},
	{Leaderboard: 0},
	{PlatformInfo: 0},
	{LocalStorage: 0},
	{CollisongCard: 0},
	{LogoTexts: 0},
	{Sound: 0},
	{BestScore: 0},
	{Score: 0},
	{Language: 0},
	{Value: 0},
	{CreateCard: 0},
	{x: 0},
	{Frame: 0},
	{GameOver: 0},
	{Count: 0}
];

self.InstanceType = {
	btn_exit: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	buttonsss: class extends self.ISpriteInstance {},
	btnLeaderboard: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	backgroundMenu: class extends self.ISpriteInstance {},
	MobForMenu1: class extends self.ISpriteInstance {},
	MobForMenu2: class extends self.ISpriteInstance {},
	MobForMenu3: class extends self.ISpriteInstance {},
	MobForMenu4: class extends self.ISpriteInstance {},
	MobForMenu6: class extends self.ISpriteInstance {},
	MobForMenu7: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	boardSettings: class extends self.ISpriteInstance {},
	btnClose: class extends self.ISpriteInstance {},
	btnFullscreen: class extends self.ISpriteInstance {},
	btnLanguage: class extends self.ISpriteInstance {},
	btnSound: class extends self.ISpriteInstance {},
	_9patch: class extends self.IWorldInstance {},
	LogoBestScoretext: class extends self.ISpriteInstance {},
	LogoTextLanguage: class extends self.ISpriteInstance {},
	TextLogoScore: class extends self.ISpriteInstance {},
	numer2: class extends self.ISpriteInstance {},
	numer3: class extends self.ISpriteInstance {},
	Texts: class extends self.ITextInstance {},
	Avatar1: class extends self.ISpriteInstance {},
	Avatar10: class extends self.ISpriteInstance {},
	Avatar2: class extends self.ISpriteInstance {},
	Avatar3: class extends self.ISpriteInstance {},
	Avatar4: class extends self.ISpriteInstance {},
	Avatar5: class extends self.ISpriteInstance {},
	Avatar6: class extends self.ISpriteInstance {},
	Avatar7: class extends self.ISpriteInstance {},
	Avatar8: class extends self.ISpriteInstance {},
	Avatar9: class extends self.ISpriteInstance {},
	boardLeaderboard: class extends self.ISpriteInstance {},
	btnCloseLeaderboard: class extends self.ISpriteInstance {},
	linePosPlayer: class extends self.ISpriteInstance {},
	HighScoreLogo: class extends self.ISpriteInstance {},
	btnHome: class extends self.ISpriteInstance {},
	GameBackground: class extends self.ITiledBackgroundInstance {},
	spawnCard: class extends self.ISpriteInstance {},
	ic_card_: class extends self.ISpriteInstance {},
	lineCard: class extends self.ISpriteInstance {},
	ScoreText: class extends self.ITextInstance {},
	LockParticles: class extends self.IParticlesInstance {},
	numer: class extends self.ISpriteInstance {},
	ScoreLogo: class extends self.ISpriteInstance {},
	boardGameOver: class extends self.ISpriteInstance {},
	btnOverHome: class extends self.ISpriteInstance {},
	btnOverRetry: class extends self.ISpriteInstance {},
	OverLogo: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Leaderboard: class extends self.IArrayInstance {},
	PlatformInfo: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	CollisongCard: class extends self.ISpriteInstance {},
	LogoTexts: class extends self.ISpriteInstance {}
}